<a href="https://colab.research.google.com/github/GiselyKCosta/SentimentAPI-Hackathon_ONE/blob/modelagem/SentimentAPI_modelagem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TEXTE API KaGGLE

In [5]:
# Instala a biblioteca Kaggle
!pip install -q kaggle
import os

# 1. Configurar a Chave e o Usuário (Substitua pelos seus dados)
# NOTA: O nome de usuário do Kaggle pode ser encontrado no seu perfil.
# A chave de API (key) é a chave que você copiou após gerar o token.

KAGGLE_USERNAME = "emanuel"  # Ex: "emanuel" (conforme a imagem)
KAGGLE_KEY = "KGAT_61c94f10a87d87f193655a905521899b"              # Ex: "7a29e92d8f94..." (A chave que você copiou)

# 2. Criar a estrutura de diretórios e o arquivo kaggle.json

# Cria a pasta .kaggle (se não existir)
!mkdir -p ~/.kaggle

# Conteúdo do arquivo kaggle.json no formato JSON
kaggle_json_content = f'{{"username":"{KAGGLE_USERNAME}", "key":"{KAGGLE_KEY}"}}'

# Escreve o conteúdo no arquivo kaggle.json
with open(os.path.expanduser('~/.kaggle/kaggle.json'), 'w') as f:
    f.write(kaggle_json_content)

# 3. Garante que o arquivo tenha as permissões corretas
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d olistbr/brazilian-ecommerce

Dataset URL: https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce
License(s): CC-BY-NC-SA-4.0
Downloading brazilian-ecommerce.zip to /content
  0% 0.00/42.6M [00:00<?, ?B/s]
100% 42.6M/42.6M [00:00<00:00, 1.26GB/s]

In [8]:
import zipfile
import pandas as pd
import os

zip_file_name = 'brazilian-ecommerce.zip'
extracted_folder = 'olist_data'
os.makedirs(extracted_folder, exist_ok=True)

# Descompacta o arquivo principal
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    print(f"Descompactando {zip_file_name}...")
    zip_ref.extractall(extracted_folder)

print("Arquivos CSV descompactados com sucesso.")

# Exemplo de carregamento de um arquivo:
file_to_load = os.path.join(extracted_folder, 'olist_order_reviews_dataset.csv')
df_orders = pd.read_csv(file_to_load)
print("\nPrimeiras linhas do dataset de Pedidos (Orders):")
print(df_orders.head())

Descompactando brazilian-ecommerce.zip...
Arquivos CSV descompactados com sucesso.

Primeiras linhas do dataset de Pedidos (Orders):
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

In [12]:
df_reviews = df_orders.drop(columns=['order_id','review_id','review_creation_date','review_answer_timestamp'])
df_reviews.head()

,review_score,review_comment_title,review_comment_message
0,4,NaN,NaN
1,5,NaN,NaN
2,5,NaN,NaN
3,5,NaN,Recebi bem antes do prazo estipulado.
4,5,NaN,Parabéns lojas lannister adorei comprar pela I...

In [19]:
df_reviews.shape

(99224, 3)

In [31]:
COLUNAS_PARA_LIMPAR = ['review_comment_title', 'review_comment_message']
df_reviews_limpo = df_reviews.dropna(
    subset=['review_comment_title', 'review_comment_message'],
    how='all'
)

print(f"Dataset Original: {df_reviews_limpo.shape[0]} linhas")

df_reviews_limpo.head()

Dataset Original: 42706 linhas

,review_score,review_comment_title,review_comment_message
3,5,NaN,Recebi bem antes do prazo estipulado.
4,5,NaN,Parabéns lojas lannister adorei comprar pela I...
9,4,recomendo,aparelho eficiente. no site a marca do aparelh...
12,4,NaN,"Mas um pouco ,travando...pelo valor ta Boa.\r\n"
15,5,Super recomendo,"Vendedor confiável, produto ok e entrega antes..."

## EDA

##TF-IDF

NameError: name 'opa' is not defined

## Treinamento